# Generated by Django 4.0.4 on 2022-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField()),
                ('address', models.TextField()),
                ('roll_number', models.IntegerField()),
            ],
            options={
                'db_table': 'studentinfo',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField()),
                ('address', models.TextField()),
                ('compensesion', models.IntegerField()),
            ],
            options={
                'db_table': 'teacherinfo',
            },
        ),
    ]
