# Generated by Django 4.0.4 on 2022-06-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_student_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
    ]
