# Generated by Django 3.1.7 on 2021-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_publishyear',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='orders_date',
            field=models.DateField(null=True),
        ),
    ]
