# Generated by Django 4.0.4 on 2022-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_website', models.URLField()),
                ('product_image', models.ImageField(upload_to='resources/')),
                ('product_manf_date', models.DateField()),
            ],
        ),
    ]
