# Generated by Django 4.0.4 on 2022-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Employee's First Name")),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Employee's Last Name")),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, verbose_name="Employee's Mobile Number")),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profileimage', models.ImageField(upload_to='images/employee/')),
            ],
            options={
                'db_table': 'employeeinfo',
            },
        ),
    ]
