# Generated by Django 4.0.4 on 2022-05-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
    ]
