# Generated by Django 4.0.4 on 2022-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profileimage',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
