# Generated by Django 4.0.4 on 2022-05-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher_student_teacher_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
