# Generated by Django 3.1 on 2022-06-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
